### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ydmo** [bwasti/AICamera#11]
please help, Thanks a lot
Click the green play button and error came up

$ adb shell am start -n "com.example.aicamera/com.example.aicamera.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.example.aicamera/com.example.aicamera.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.example.aicamera/.MainActivity }
Error type 3
Error: Activity class {com.example.aicamera/com.example.aicamera.MainActivity} does not exist.

Error while Launching activity

**Comment by zchrissirhcz** [comment]
If you use Android Studio, try removing `.idea` and `.gradle` folders under this project. Then click the green play button again.

**Comment by marseel** [comment]
I got the same problem, right now I am installing application using console:
`adb install -r app/build/outputs/apk/app-debug.apk`
and then running manually and it works.

**Comment by bwasti** [comment]
total overhaul, does the same issue exist?

**Comment by marseel** [comment]
It doesn't exist anymore. Thank you for great update, I really appreciate it :)
