### ISSUE TITLE
slower than tensorflow?

### ISSUE THREAD

**Issue by lzx1413** [bwasti/AICamera#12]
It takes about 1.3-1.6s to process one image with this app while tf android demo takes only less than 0.5s. in caffe2, Squeeze net is used while tf uses incepitonv2, Is there anything wrong when build this app or I forget to add some accelerate support options?

**Comment by bwasti** [comment]
this has to do with the build system not specifying the O3 flag appropriately, I am currently in the process of rewriting this application entirely to use caffe2's build_android.sh script rather than the flaky gradle/cmake setup I wrote.

**Comment by marseel** [comment]
Could you also make sure that with new build system the whole caffe2 library is not rebuild each time you try to run application (even without any changes)?
Thanks :)

**Comment by bwasti** [comment]
rewrite is now up

**Comment by lzx1413** [comment]
thanks :)
