### ISSUE TITLE
Image Channel Mean Subtraction?

### ISSUE THREAD

**Issue by StanislawAntol** [bwasti/AICamera#13]
Looking at the [Caffe2 tutorial on model loading](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Loading_Pretrained_Models.ipynb), it has the lines:
```
# if you have a mean file, place it in the same dir as the model
MODEL = 'squeezenet', 'init_net.pb', 'predict_net.pb', 'ilsvrc_2012_mean.npy', 227
```
which suggests that the SqueezeNet model (there's no information on where it comes from...) expects input images with the ImageNet mean values subtracted off (and maybe not restrict the subtracted input to be between 0-255?). For your convenience, those channel mean values are:
```
float b_mean = 104.00698793f;
float g_mean = 116.66876762f;
float r_mean = 122.67891434f;
```
I wasn't sure how to rebuild the native-lib.cpp file, so I couldn't test it out, but I would expect it to give better classification results.

Also, I found it very confusing swapping around [r_i, g_i, b_i in the color conversion](https://github.com/bwasti/AICamera/blob/master/app/src/main/cpp/native-lib.cpp#L113), which doubles as RGB -> BGR conversion due to the naming. I think it would be cleaner to change the multipliers for r_i, g_i, and b_i and then use them in the expected order for YUV conversion.

**Comment by bwasti** [comment]
ah great catch(es)!  a sloppy conversion on my part (the demo originally featured a different model).
