### ISSUE TITLE
change caffe2model

### ISSUE THREAD

**Issue by xqpinitial** [bwasti/AICamera#2]
Thanks for your AiCamera demo.
I build it and run on my android mobile,there is no problem
when i try to change  model ,there is a problem .every time when i open AI camera app,it will shut down .
i use caffe_translator_test to translate google_net.caffemodel to .pb  and in neuralnet-lib.cpp i also change const int predHeight = 224; //#128

**Comment by Jia-HongHenryLee** [comment]
@xqpinitial  Solution: Manually go into the directory and run the script.

http://caffe2.ai/docs/AI-Camera-demo-android.html

**Comment by victorv** [comment]
is predHeight == to predWidth?

**Comment by bwasti** [comment]
this should be fixed in overhaul
