### ISSUE TITLE
Crashing on Samsung Galaxy S5: assertion "IMG_H <= h" failed

### ISSUE THREAD

**Issue by cmaurya11** [bwasti/AICamera#23]
Crashing on Samsung Galaxy S5 running Android 6.0.1

Message in logcat:

facebook.f8demo A/libc: /AICamera-master/app/src/main/cpp/native-lib.cpp:86: jstring Java_facebook_f8demo_ClassifyCamera_classificationFromCaffe2(JNIEnv *, jobject, jint, jint, jbyteArray, jbyteArray, jbyteArray, jint, jint, jboolean): assertion "IMG_H <= h" failed

**Comment by cmaurya11** [comment]
Got it to work by commenting out the assertion statements on line 86 and 87 in native-lib.cpp

    //assert(IMG_H <= h);
    //assert(IMG_W <= w);

Now seems to work, but crashes after some time with different error message:

/facebook.f8demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xd9322d4d in tid 27391 (Camera Backgrou)

**Comment by bwasti** [comment]
should work now, feel free to reopen if it doesn't
