### ISSUE TITLE
Cannot run the app on Android Studio 2.3.2, Windows

### ISSUE THREAD

**Issue by LeenaShekhar** [bwasti/AICamera#26]
Device supports x86, but apk only supports armeabi-v7a. As suggested by one of the stackoverflow posts I change "abiFilters  'armeabi-v7a'" to "abiFilters  'armeabi-v7a', "x86"" then I get an error "Error:error: '../../../../src/main/jniLibs/x86/libcaffe2.a', needed by '../../../../build/intermediates/cmake/debug/obj/x86/libnative-lib.so', missing and no known rule to make it".

How can I fix this? Is this because I am using Windows? Should I try using Ubuntu?

**Comment by bwasti** [comment]
You'll need to build caffe2 for android x86 and copy the relevant library files over into that folder you just created.

take this [script](https://github.com/caffe2/caffe2/blob/master/scripts/build_android.sh#L54) and change that line to x86 to compile it for x86 android

**Comment by ajbolous** [comment]
I am trying to build caffe2 for android x86, yet it fails while linking to libprotobuf.a any known fix ?
