### ISSUE TITLE
Where are the caffe2 binaries for android?

### ISSUE THREAD

**Issue by xhsoldier** [bwasti/AICamera#29]
I built caffe2 for android by this: ./scripts/build_android.sh
but where is the generated binaries?

libCAFFE2_NNPACK.a or libCAFFE2_PTHREADPOOL.a or libCaffe2_CPU.a?
libCAFFE2_NNPACK.a is 328kb
libCAFFE2_PTHREADPOOL.a is 8kb
libCaffe2_CPU.a is 304M

Caffe2 binaries used by AICamera, I can not generate these libraries.

**Comment by bwasti** [comment]
check to confirm they exist:

    find . |grep -E ".*\.a$"

and that should also give you enough info to find them.

**Comment by xumengwei** [comment]
Hi @bwasti , I tried to find the .a files and the result turns out to be 
```
./build_android/lib/libcaffe2.a
./build_android/lib/libcpufeatures.a
./build_android/lib/libnnpack.a
./build_android/lib/libnnpack_reference_layers.a
./build_android/lib/libprotobuf-lite.a
./build_android/lib/libprotobuf.a
./build_android/lib/libpthreadpool.a
./build_host_protoc/build/libprotobuf-lite.a
./build_host_protoc/build/libprotobuf.a
./build_host_protoc/build/libprotoc.a
./build_host_protoc/lib/libprotobuf-lite.a
./build_host_protoc/lib/libprotobuf.a
./build_host_protoc/lib/libprotoc.a
```
Seems like still misses some binaries used in this demo such as _libCaffe2_CPU.a_. Do u have any idea how to deal with this?
