### ISSUE TITLE
AI camera demo success, and do not use the caffe2 library, why?

### ISSUE THREAD

**Issue by wuyubuaa** [bwasti/AICamera#33]
@bwasti Hi，thanks for your demo first! But I have a question about it , I use android studio opened the AI camera poeject, and run the dome on my android phone, I do not use the  build_android.sh to generate the caffe2 library on android platform, but I run the demo successfully, Why?

**Comment by daimagou** [comment]
Hi @wuyubuaa The caffe2 libary location is:/AICamera/app/src/main/jniLibs/armeabi-v7a/
You can replace it.
