### ISSUE TITLE
Does not build under Windows

### ISSUE THREAD

**Issue by salos1982** [bwasti/AICamera#4]
There is no AICamera/app/libs/caffe2/scripts/build_host_protoc.sh for windows

**Comment by zchrissirhcz** [comment]
There is `AICamera/app/libs/caffe2/scripts/build_host_protoc.sh` on windows. It just can run.

**Comment by salos1982** [comment]
Yes it is but it cannot be run on Windows. It is *nix shell script.

**Comment by ahmedezzateasa** [comment]
It is not building with me too in windows.
I created a batch script "build_host_protoc.bat"

```
@echo off
SET CAFFE2_ROOT=D:\git_clones\AICamera\app\libs\caffe2
SET BUILD_ROOT=%CAFFE2_ROOT%\build_host_protoc
SET BUILD_DIR=%BUILD_ROOT%\build
SET BIN_DIR=%BUILD_ROOT%\bin
SET CMAKE="C:\Program Files\CMake\bin\cmake.exe"

:: Create the build directory for VS projects
IF EXIST %BUILD_DIR% (
del %BUILD_DIR%
)
mkdir %BUILD_DIR%

:: BIN directory where protoc.exe must exist
IF NOT EXIST %BIN_DIR% (
mkdir %BIN_DIR%
)

cd %BUILD_DIR%
:: Run CMAKE to generate a Visual Studio Solution
%CMAKE% %CAFFE2_ROOT%\third_party\protobuf\cmake -DCMAKE_INSTALL_PREFIX=%BUILD_ROOT% -Dprotobuf_BUILD_TESTS=OFF
:: Build the solution
devenv protobuf.sln /Build "Debug|Win32"
copy Debug\protoc.exe %BIN_DIR% /Y

````
The app/build.gradle must be changed "instead of .sh use the .bat file"

This requires Visual Studio to be installed (I am using Visual Studio Community 2015) and the devenv.exe seen by the windows PATH variable (add VS_HOME_DIR\Common7\IDE to Path Environment variable)

**Comment by Worhavah** [comment]
win64 cannot run?

**Comment by codeloverr** [comment]
@ahmedezzateasa I am trying to run bat file but I am getting an error `'devenv' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.`

Can you guide me? I have tried to add devenv to system variable but same problem.

**Comment by salos1982** [comment]
> This requires Visual Studio to be installed (I am using Visual Studio Community 2015) and the devenv.exe seen by the windows PATH variable (add VS_HOME_DIR\Common7\IDE to Path Environment variable)
Also CMAKE to be installed.

**Comment by codeloverr** [comment]
I have VS 2015 and Cmake installed aslo added Path variable but not working.

**Comment by ahmedezzateasa** [comment]
You need to add the MS_VISUAL_STUDIO_HOME/Common7/IDE to your path.
This is where devenv.exe is located. You can try to type devenv.exe on cmd line to test it is working first.

**Comment by codeloverr** [comment]
@ahmedezzateasa  kindly check. If I'm doing something wrong guide plz.

![1](https://cloud.githubusercontent.com/assets/12197291/25289950/4534ec72-26e5-11e7-85c7-0f6e0c803d8e.PNG)
![2](https://cloud.githubusercontent.com/assets/12197291/25289951/453bfec2-26e5-11e7-83b4-97aff220f658.PNG)

**Comment by salos1982** [comment]
you do not need to add environment variable "devenv". you need add devenv director to system variable "path" to variable 
![image](https://cloud.githubusercontent.com/assets/2404581/25302198/59fc7c22-2741-11e7-9a57-e5fe77feb963.png)

**Comment by codeloverr** [comment]
After successfully running the bat file, issue #6  doesn't resolve.

**Comment by ahmedezzateasa** [comment]
@codeloverr You must change app/build.gradle to use the .bat file instead of .sh (See line 9)

**Comment by bwasti** [comment]
Ideally you could add this to Caffe2, as that is where the build scripts exist :)

**Comment by codeloverr** [comment]
@ahmedezzateasa Thank you for your help, issue resolved :)
