### ISSUE TITLE
java.lang.RuntimeException: Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by Jia-HongHenryLee** [bwasti/AICamera#5]
hello, everyone,
  
    I try to build AlCamera in Asus Zenbo device (android 6.0), and get this error message:
    java.lang.RuntimeException: Camera is being used after Camera.release() was called

    how to solve this problem in MainActivity.java ??

thank everyone.

**Comment by Jia-HongHenryLee** [comment]
solution: in AndroidManifest.xml
     change android:screenOrientation become landscape

**Comment by codeloverr** [comment]
@Jia-HongHenryLee You running project in Android Studio on Windows?

**Comment by Jia-HongHenryLee** [comment]
@codeloverr  i run this project in Android Studio on Ubuntu, and try to build in Asus Zenbo device (android 6.0). I find that the orientation of screen in asus zenbo is landscape mode, not portrait mode. By the way, i also try to build in Asus zenfone3 device ( android 7.0), and this project can successfully to build it.
