### ISSUE TITLE
Gradle Build error in Android Studio on Windows

### ISSUE THREAD

**Issue by codeloverr** [bwasti/AICamera#6]
When I am trying to import project in Android Studio after cloning and running other commands. I got following error 
`Error:CreateProcess error=193, %1 is not a valid Win32 application`

**Comment by ahmedezzateasa** [comment]
I faced same error. The app/libs/caffe2/scripts/build_host_protoc.sh is not valid for windows.
I wrote my .bat file and I can successfully get the application build successfully.
See my comment on a related issue [4](https://github.com/bwasti/AICamera/issues/4)

**Comment by bwasti** [comment]
this is actually an issue with caffe2, not the application.  If you don't mind, please post there about building for android under windows
