### ISSUE TITLE
change shufflenet model load model error

### ISSUE THREAD

**Issue by cswwp** [bwasti/AICamera#65]
I have converted pytorch shufflenet model to pb model, and test it ok on pc with these pb model, but when i replace the assert model, and debug model run with android studio, it crashed when run "_predictor = new caffe2::Predictor(_initNet, _predictNet);", pb file is tested on pc, but can't run in android studio...how fix it?

**Comment by cswwp** [comment]
@machoji @ThomasGueldner @FullZing @jazzseow @northeastsquare

**Comment by orionr** [comment]
@cswwp were you able to resolve this? If so, please post the resolution for others. Thanks.
